// <auto-generated />
namespace Kcsara.Database.Web.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class InitialMigration : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201209062229338_InitialMigration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAN1YzW7bOBC+L9B3EHTqHmomaQ9pILdw7aRrtE6CKknPtDS2iVKkVqQC+9l66CPtK+zoX6ZsWf5pUfRiWOTMNz+c4afRf99/OO+XAbeeIVJMir593juzLRCe9JmY9+1Yz15d2u/fvfjLufaDpfVUyL1O5FBTqL690Dq8IkR5Cwio6gXMi6SSM93zZECoL8nF2dlbcn5OACFsxLIs50ssNAsgfcDHoRQehDqmfCJ94Cpfxx03RbVuaQAqpB707U+eohHtjaimU6qg9xWmvVTLtgacUXTIBT6zrfDN1aMCV0dSzN2Qakb5wyoE3J9RriB3/yp80zWCs4skAkKFkBrhpDgoA3YZG0Z3jVnQq8StNMK+PQG1uMVgXLQQq7osSn+C1doCLt1HMoRIr77ALEcYj2yLrOsRU7FUq+kkTuA/oV9f2NZtzDmdcihzhcl0tYzgIwiIqAb/nmoNEVbC2Ic0iIZVw0byW1jBQ8Hysq0btgT/M4i5XpSWJnRZrOBf23oUDKsRlXQUQ92z7Lnd6AOrjGLBQPbciK4d5LP08uPOgD6CnEc0XKz29WZ8P/D96Jcn4THUtTS4aJTvn4QP6XmvniTX6kiof2Ss4BRAA56UIMW63B/NIVXvderIsgoO6Mms9sluwaw+923fA1rr/OKypao6Zf/X9dbex4d0oinDm8o4w3SXgXmvZkou6Fx8uADvGxNYUJWRjFV6xv1sRmciFeG1QVUp2BRgGUpFiSTjxII7yRbydCY0DLEWamSar1huxqTDV+7+FBZkGMRTG5is9La0hM1J52Dsomn09IZFShc0bltDP2iIdT24wpxxfmbDVWdQKCT/M6WtrxXmmRugVVpvMNIAyTANGkrf2kk9h3A9ymm0gZaHkseB2EbtbdrZrVDX33wNbUfIOrqOsOl+akOoaruOsrnid+Qi5861fORr3VEKKqyjFGvdUda5sI61vtMdsU6Jdbz6ene0Bi/WIRubTVyH"
                       + "GBVt9hFpNJLBWGZjdmrb6rI8bd9uZu4UuGvnbof4s7rvp558g9JMkdJ6SW0GhTk5neweEhv8konYFqbomfkJt7grpSFIC6fn/suHnGG8lcCECjYDpR/kN8AxB+nv0hgwDxj+iFI+/70nQJYkYeest+drXv0NVTzTyFvQ6GVAl38fM9D56Js+xUvn/DQD3VGBrQ9pEVB+khHtIKDmgHYQzJbxrAPWnzqcFRXSHMWOmL1+bhscPXs13/TbRyZzwto5gmU3O+ZhKjGSzOs9x7TmKNZhWmuzW5v7DhzqmkznkPpHU2cEis0riOQTqgAvMVqBFjJjMZPF4WPUdY8KEaM2JqApFhYdRJrNqKdx2wOl0k8LT5THKHIdTMEfi7tYh7EeKAXBlK99BXRIu/10cl332bkL07SdIgR0kyW9cSc+xIz7pd83Gyp6C0RSuzkLoleuTthwviqRbqXoCJSnbwQhiIRDHyAIOYKpO+HSZ9ju2+4crmfMGTGKTRyoHKPST77hk+Qj/rv/AQ+SwXz2FwAA"; }
        }
    }
}
