// <auto-generated />
namespace Sar.Auth.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class LogoutUris : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(LogoutUris));
        
        string IMigrationMetadata.Id
        {
            get { return "201609142243515_LogoutUris"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
