// <auto-generated />
namespace Kcsar.Database.Model.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class MemberExternalKey : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MemberExternalKey));
        
        string IMigrationMetadata.Id
        {
            get { return "201307200720558_MemberExternalKey"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
