// <auto-generated />
namespace Kcsar.Database.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class TrainingRosterKeys : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TrainingRosterKeys));
        
        string IMigrationMetadata.Id
        {
            get { return "201701041543513_TrainingRosterKeys"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
