// <auto-generated />
namespace Kcsar.Database.Model.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Member_SheriffApp : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Member_SheriffApp));
        
        string IMigrationMetadata.Id
        {
            get { return "201209070517147_Member_SheriffApp"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
