// <auto-generated />
namespace Kcsar.Database.Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class MemberStatus : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MemberStatus));
        
        string IMigrationMetadata.Id
        {
            get { return "201308090456333_MemberStatus"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
