// <auto-generated />
namespace Kcsar.Database.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class DataModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DataModel));
        
        string IMigrationMetadata.Id
        {
            get { return "201504040626075_DataModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
