//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sar.Auth {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sar.Auth.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account is locked.
        /// </summary>
        internal static string AccountLocked {
            get {
                return ResourceManager.GetString("AccountLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification code not found or is invalid.
        /// </summary>
        internal static string BadVerification {
            get {
                return ResourceManager.GetString("BadVerification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login is already registered.
        /// </summary>
        internal static string ExternalLoginAlreadyRegistered {
            get {
                return ResourceManager.GetString("ExternalLoginAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not available for registration.
        /// </summary>
        internal static string ExternalLoginNotAvailable {
            get {
                return ResourceManager.GetString("ExternalLoginNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not logged in with external login..
        /// </summary>
        internal static string NotLoggedInExternalLogin {
            get {
                return ResourceManager.GetString("NotLoggedInExternalLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KCSARA Login Service.
        /// </summary>
        internal static string ThisServiceName {
            get {
                return ResourceManager.GetString("ThisServiceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown User.
        /// </summary>
        internal static string UnknownUserName {
            get {
                return ResourceManager.GetString("UnknownUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username or password is not correct.
        /// </summary>
        internal static string UserPasswordNotCorrect {
            get {
                return ResourceManager.GetString("UserPasswordNotCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your code: {0}.
        /// </summary>
        internal static string VerifyMessageHtml {
            get {
                return ResourceManager.GetString("VerifyMessageHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KCSARA Verification Code.
        /// </summary>
        internal static string VerifyMessageSubject {
            get {
                return ResourceManager.GetString("VerifyMessageSubject", resourceCulture);
            }
        }
    }
}
